import { 
  LucideIcon, 
  MoreVertical, 
  Edit, 
  Trash2, 
  Plus, 
  X, 
  ArrowLeft, 
  ArrowRight, 
  Search, 
  Settings, 
  Home, 
  Library, 
  Podcast, 
  Play, 
  Download, 
  Upload, 
  Info, 
  AlertCircle, 
  AlertTriangle, 
  Check, 
  ChevronDown, 
  ChevronUp,
  Mail,
  User,
  Lock,
  LogOut,
  RefreshCw,
  Filter,
  SortAsc,
  Grid,
  List,
  Menu,
  MoreHorizontal,
  Clock,
  Calendar,
  VolumeX,
  Volume1,
  Volume2,
  BookOpen,
  ListPlus,
  CheckSquare,
  Pause,
  Rss,
  Folder,
  FolderPlus,
  ChevronLeft,
  ChevronRight,
  HelpCircle,
  FileText,
  ExternalLink,
  Smartphone,
  Shield,
  Key,
  Database,
  History,
  HardDrive,
  Activity
} from 'lucide-react'

export const iconMap: Record<string, LucideIcon> = {
  more_vert: MoreVertical,
  more_horiz: MoreHorizontal,
  edit: Edit,
  delete: Trash2,
  add: Plus,
  close: X,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  search: Search,
  settings: Settings,
  home: Home,
  library_books: Library,
  podcasts: Podcast,
  play_arrow: Play,
  download: Download,
  upload: Upload,
  info: Info,
  error: AlertCircle,
  warning: AlertTriangle,
  check: Check,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  email: Mail,
  person: User,
  lock: Lock,
  logout: LogOut,
  refresh: RefreshCw,
  filter_list: Filter,
  sort: SortAsc,
  grid_view: Grid,
  view_list: List,
  menu: Menu,
  schedule: Clock,
  event: Calendar,
  volume_off: VolumeX,
  volume_down: Volume1,
  volume_up: Volume2,
  auto_stories: BookOpen,
  playlist_play: ListPlus,
  playlist_add_check: CheckSquare,
  pause: Pause,
  rss_feed: Rss,
  folder: Folder,
  create_new_folder: FolderPlus,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  help_outline: HelpCircle,
  description: FileText,
  open_in_new: ExternalLink,
  smartphone: Smartphone,
  security: Shield,
  vpn_key: Key,
  database: Database,
  history: History,
  hard_drive: HardDrive,
  reorder: Menu,
  activity: Activity
}

export const getLegacyIcon = (name: string): LucideIcon | null => {
  return iconMap[name] || null
}
