'use client'

import {
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  BadgeCheck,
  Bold,
  Bookmark,
  BookOpen,
  Check,
  CheckCheck,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleCheckBig,
  CircleHelp,
  CircleMinus,
  CirclePlus,
  Clapperboard,
  ClipboardPaste,
  Copy,
  Download,
  Edit2,
  Ellipsis,
  EllipsisVertical,
  ExternalLink,
  Eye,
  EyeOff,
  FileUp,
  FolderOpen,
  GripVertical,
  Heart,
  Home,
  IndentDecrease,
  IndentIncrease,
  Info,
  Italic,
  LibraryBig,
  Link2,
  List,
  ListFilter,
  ListOrdered,
  type LucideIcon,
  type LucideProps,
  Maximize2,
  Menu,
  MessageCircle,
  Minus,
  MoreHorizontal,
  Pause,
  Pencil,
  Play,
  Plus,
  Quote,
  Redo2,
  RefreshCw,
  Scissors,
  Search,
  Settings,
  Share2,
  SkipBack,
  SkipForward,
  SlidersHorizontal,
  Square,
  SquarePen,
  Strikethrough,
  Trash2,
  TriangleAlert,
  Underline,
  Undo2,
  Unlink,
  Upload,
  User,
  Users,
  Volume1,
  Volume2,
  VolumeX,
  X,
} from 'lucide-react'

const iconAliases: Record<string, LucideIcon> = {
  add: Plus,
  add_circle: CirclePlus,
  auto_stories: BookOpen,
  align_center: AlignCenter,
  align_justify: AlignJustify,
  align_left: AlignLeft,
  align_right: AlignRight,
  arrow_back: ArrowLeft,
  arrow_downward: ArrowDown,
  arrow_forward: ArrowRight,
  arrow_upward: ArrowUp,
  beenhere: CircleCheckBig,
  bookmark: Bookmark,
  bookmark_border: Bookmark,
  badge: BadgeCheck,
  check: Check,
  check_circle: CircleCheckBig,
  circle: Circle,
  create: SquarePen,
  cut: Scissors,
  drag_indicator: GripVertical,
  edit_2: Edit2,
  error: CircleAlert,
  favorite: Heart,
  folder_open: FolderOpen,
  group: Users,
  local_movies: Clapperboard,
  local_play: Play,
  person: User,
  radio_button_unchecked: Circle,
  select_all: CheckCheck,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  close: X,
  content_copy: Copy,
  content_paste: ClipboardPaste,
  delete: Trash2,
  done: Check,
  done_all: CheckCheck,
  download: Download,
  edit: Pencil,
  event: CircleCheckBig,
  expand_less: ChevronUp,
  expand_more: ChevronDown,
  file_upload: FileUp,
  filter_list: ListFilter,
  format_align_center: AlignCenter,
  format_align_justify: AlignJustify,
  format_align_left: AlignLeft,
  format_align_right: AlignRight,
  format_bold: Bold,
  format_indent_decrease: IndentDecrease,
  format_indent_increase: IndentIncrease,
  format_italic: Italic,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  format_quote: Quote,
  format_strikethrough: Strikethrough,
  format_underlined: Underline,
  fullscreen: Maximize2,
  fullscreen_exit: Maximize2,
  grid_view: Menu,
  help: CircleHelp,
  home: Home,
  info: Info,
  keyboard_arrow_down: ChevronDown,
  keyboard_arrow_up: ChevronUp,
  library_books: LibraryBig,
  link: Link2,
  list: List,
  menu: Menu,
  more_horiz: Ellipsis,
  more_horizontal: MoreHorizontal,
  more_vert: EllipsisVertical,
  notifications: MessageCircle,
  open_in_new: ExternalLink,
  pause: Pause,
  play_arrow: Play,
  redo: Redo2,
  refresh: RefreshCw,
  remove: Minus,
  remove_circle: CircleMinus,
  search: Search,
  settings: Settings,
  share: Share2,
  skip_next: SkipForward,
  skip_previous: SkipBack,
  sort: ArrowUpDown,
  stop: Square,
  tune: SlidersHorizontal,
  undo: Undo2,
  unlink: Unlink,
  upload: Upload,
  visibility: Eye,
  visibility_off: EyeOff,
  volume_down: Volume1,
  volume_mute: VolumeX,
  volume_off: VolumeX,
  volume_up: Volume2,
  warning: TriangleAlert,
  watch_later: Play,
}

const iconLabels: Record<string, string> = {
  add: 'Increase',
  arrow_back: 'Back',
  arrow_forward: 'Forward',
  beenhere: 'Finished',
  bookmark: 'Bookmark',
  check: 'Done',
  check_circle: 'Already in library',
  chevron_left: 'Scroll left',
  chevron_right: 'Scroll right',
  close: 'Close',
  content_copy: 'Copy',
  delete: 'Delete',
  done: 'Done',
  download: 'Download',
  edit: 'Edit',
  expand_less: 'Collapse',
  expand_more: 'Expand',
  file_upload: 'Upload file',
  filter_list: 'Filter',
  format_bold: 'Bold',
  format_italic: 'Italic',
  format_list_bulleted: 'Bulleted list',
  format_list_numbered: 'Numbered list',
  format_strikethrough: 'Strikethrough',
  format_underlined: 'Underline',
  fullscreen: 'Fullscreen',
  help: 'Help',
  home: 'Home',
  info: 'Information',
  local_movies: 'Trailer',
  local_play: 'Bonus',
  keyboard_arrow_down: 'Expand',
  keyboard_arrow_up: 'Collapse',
  link: 'Link',
  more_horiz: 'More options',
  more_vert: 'More options',
  notifications: 'Notifications',
  open_in_new: 'Open in new tab',
  pause: 'Pause',
  play_arrow: 'Play',
  redo: 'Redo',
  refresh: 'Refresh',
  remove: 'Decrease',
  search: 'Search',
  settings: 'Settings',
  share: 'Share',
  skip_next: 'Skip forward',
  skip_previous: 'Skip backward',
  sort: 'Sort',
  stop: 'Stop',
  tune: 'Adjust',
  undo: 'Undo',
  unlink: 'Remove link',
  upload: 'Upload',
  visibility: 'Show',
  visibility_off: 'Hide',
  volume_down: 'Volume down',
  volume_mute: 'Mute',
  volume_off: 'Mute',
  volume_up: 'Volume up',
  warning: 'Warning',
}

function normalizeIconName(name: string): string {
  return name
    .trim()
    .toLowerCase()
    .replace(/[\s-]+/g, '_')
}

export function getIconForName(name: string): LucideIcon {
  return iconAliases[normalizeIconName(name)] ?? CircleHelp
}

export function getIconLabel(name: string): string {
  const normalized = normalizeIconName(name)
  return iconLabels[normalized] ?? normalized.replace(/_/g, ' ')
}

export interface AppIconProps extends Omit<LucideProps, 'ref'> {
  name: string
  fallback?: LucideIcon
}

export default function AppIcon({ name, fallback = CircleHelp, ...props }: AppIconProps) {
  const normalized = normalizeIconName(name)
  const Icon = iconAliases[normalized] ?? fallback
  return <Icon aria-hidden="true" data-icon-name={name} {...props} />
}
