import { createServiceRoleClient } from '@/utils/supabase/service-role'
import { createClient as createSupabaseClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'
import { fetchBookCover } from '@/lib/coverFetch'
import { checkB2ObjectExists } from '@/lib/storageSync'

/**
 * POST /api/upload
 *
 * Receives JSON metadata after files have already been uploaded directly
 * to Supabase Storage from the browser. Creates the DB records:
 *   books → library_items (media_id → books.id) → book_authors / book_series
 *
 * Auth: JWT from Authorization: Bearer header.
 *
 * Body (JSON):
 *   bookId        - UUID pre-generated by the client (storage path prefix)
 *   title         - item title
 *   author        - author name (optional)
 *   series        - series name (optional)
 *   library       - library UUID
 *   mediaType     - 'book' | 'podcast'
 *   files         - array of { name, size, type, storagePath }
 */
export async function POST(request: NextRequest) {
  // ── 1. Verify JWT ─────────────────────────────────────────────────────────
  const authHeader = request.headers.get('authorization')
  const token = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null

  if (!token) {
    console.error('[api/upload] Missing token in Authorization header')
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const anonClient = createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
  const { data: { user }, error: userError } = await anonClient.auth.getUser(token)

  if (userError || !user) {
    console.error('[api/upload] User verification failed:', userError?.message || 'No user found')
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // ── 2. Check admin/root ───────────────────────────────────────────────────
  const db = createServiceRoleClient()

  const { data: profile } = await db
    .from('profiles')
    .select('user_type')
    .eq('id', user.id)
    .single()

  if (!profile || !['admin', 'root'].includes(profile.user_type ?? '')) {
    return NextResponse.json({ error: 'Forbidden — admin or root required' }, { status: 403 })
  }

  // ── 3. Parse JSON body ────────────────────────────────────────────────────
  let body: {
    bookId: string
    title: string
    author?: string
    series?: string
    library: string
    mediaType?: string
    files: { name: string; size: number; type: string; storagePath: string }[]
  }

  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { bookId, title, author = '', series = '', library: libraryId, mediaType = 'book', files } = body

  if (!bookId || !title || !libraryId || !files?.length) {
    return NextResponse.json({ error: 'Missing required fields: bookId, title, library, files' }, { status: 400 })
  }

  // ── 3b. Verify files exist in storage before creating DB records ─────────
  const missingFiles: string[] = []
  for (const file of files) {
    if (process.env.B2_ENDPOINT && process.env.B2_BUCKET_NAME) {
      const exists = await checkB2ObjectExists(file.storagePath)
      if (!exists) missingFiles.push(file.storagePath)
    } else {
      // Check Supabase Storage
      const { data } = await db.storage.from('audio').download(file.storagePath)
      if (!data) missingFiles.push(file.storagePath)
    }
  }

  if (missingFiles.length > 0) {
    console.warn(`[upload] ${missingFiles.length} files not found in storage:`, missingFiles)
    return NextResponse.json(
      {
        error: `${missingFiles.length} file(s) not found in storage. Upload files first.`,
        missingFiles,
      },
      { status: 400 }
    )
  }

  const libraryItemId = crypto.randomUUID()
  const totalSize = files.reduce((sum, f) => sum + f.size, 0)

  // ── 4. Build audio_files JSONB ────────────────────────────────────────────
  const audioFilesJson = files.map((file, i) => ({
    index: i,
    ino: crypto.randomUUID(),
    metadata: {
      filename: file.name,
      ext: '.' + (file.name.split('.').pop()?.toLowerCase() ?? ''),
      path: file.storagePath,
      relPath: file.name,
      size: file.size,
      mtimeMs: Date.now(),
      ctimeMs: Date.now(),
      birthtimeMs: Date.now(),
    },
    addedAt: Date.now(),
    updatedAt: Date.now(),
    trackNumFromMeta: null,
    discNumFromMeta: null,
    trackNumFromFilename: null,
    discNumFromFilename: null,
    manuallyVerified: false,
    invalid: false,
    exclude: false,
    error: null,
    format: null,
    duration: null,
    bitRate: null,
    language: null,
    codec: null,
    timeBase: null,
    channels: null,
    channelLayout: null,
    chapters: [],
    embeddedCoverArt: null,
    metaTags: {},
    mimeType: file.type || 'audio/mpeg',
  }))

  // ── 5. Create or update book row (idempotent) ─────────────────────────────
  const { error: bookError } = await db
    .from('books')
    .upsert(
      { id: bookId, title, audio_files: audioFilesJson },
      { onConflict: 'id' }
    )

  if (bookError) {
    console.error('[upload] books upsert failed:', bookError)
    return NextResponse.json({ error: `Failed to create book: ${bookError.message}` }, { status: 500 })
  }

  // ── 6. Create library_item row ────────────────────────────────────────────
  const { error: itemError } = await db
    .from('library_items')
    .insert({
      id: libraryItemId,
      library_id: libraryId,
      media_type: mediaType,
      media_id: bookId,
      path: `${libraryId}/${title}`,
      rel_path: title,
      title,
      size: totalSize,
      is_missing: false,
      last_storage_check: new Date().toISOString(),
      library_files: audioFilesJson.map((af) => ({
        ino: af.ino,
        metadata: af.metadata,
        addedAt: af.addedAt,
        updatedAt: af.updatedAt,
        isSupplementary: false,
      })),
    })

  if (itemError) {
    console.error('[upload] library_items insert failed:', itemError)
    // Clean up book row
    const { error: bookCleanupError } = await db.from('books').delete().eq('id', bookId)
    if (bookCleanupError) {
      console.error('[upload] book cleanup also failed:', bookCleanupError.message)
    }
    // Clean up orphaned storage files
    const { error: storageCleanupError } = await db.storage
      .from('audio')
      .remove(files.map((f) => f.storagePath))
    if (storageCleanupError) {
      console.error('[upload] storage cleanup also failed:', storageCleanupError.message)
    }
    return NextResponse.json({ error: `Failed to create library item: ${itemError.message}` }, { status: 500 })
  }

  // ── 7. Author ─────────────────────────────────────────────────────────────
  if (author) {
    const { data: existingAuthor } = await db
      .from('authors')
      .select('id')
      .eq('name', author)
      .eq('library_id', libraryId)
      .maybeSingle()

    let authorId = existingAuthor?.id
    if (!authorId) {
      authorId = crypto.randomUUID()
      const { error: ae } = await db.from('authors').insert({ id: authorId, name: author, library_id: libraryId })
      if (ae) { console.warn('[upload] author insert failed:', ae.message); authorId = undefined }
    }

    if (authorId) {
      await db.from('book_authors').insert({ book_id: bookId, author_id: authorId })
      await db.from('library_items').update({ author_names_first_last: author }).eq('id', libraryItemId)
    }
  }

  // ── 8. Series ─────────────────────────────────────────────────────────────
  if (series) {
    const { data: existingSeries } = await db
      .from('series')
      .select('id')
      .eq('name', series)
      .eq('library_id', libraryId)
      .maybeSingle()

    let seriesId = existingSeries?.id
    if (!seriesId) {
      seriesId = crypto.randomUUID()
      const { error: se } = await db.from('series').insert({ id: seriesId, name: series, library_id: libraryId })
      if (se) { console.warn('[upload] series insert failed:', se.message); seriesId = undefined }
    }

    if (seriesId) {
      await db.from('book_series').insert({ book_id: bookId, series_id: seriesId })
    }
  }

  // ── 9. Auto-match metadata and cover art (non-blocking) ──────────────────
  // Fire and forget — don't await so the upload response is immediate.
  // This enriched data will appear after a few seconds once fetched.
  if (mediaType === 'book' && title) {
    const { fetchBookMetadata } = await import('@/lib/coverFetch')
    fetchBookMetadata(title, author || undefined)
      .then(async ({ cover, metadata }) => {
        if (!cover && !metadata) return

        // 1. Update cover if found
        let storagePath: string | undefined = undefined
        if (cover) {
          storagePath = `${libraryItemId}/cover.${cover.extension}`
          const { error: coverErr } = await db.storage
            .from('covers')
            .upload(storagePath, cover.buffer, { upsert: true, contentType: cover.contentType })
          if (coverErr) {
            console.warn('[upload] cover fetch storage failed:', coverErr.message)
            storagePath = undefined
          }
        }

        // 2. Prepare book updates
        const bookUpdates: any = {}
        if (metadata) {
          if (metadata.title) bookUpdates.title = metadata.title
          if (metadata.description) bookUpdates.description = metadata.description
          if (metadata.publishedYear) bookUpdates.published_year = metadata.publishedYear
          if (metadata.genres?.length) bookUpdates.genres = metadata.genres
          if (metadata.publisher) bookUpdates.publisher = metadata.publisher
          if (metadata.language) bookUpdates.language = metadata.language
        }
        if (storagePath) bookUpdates.cover_path = storagePath

        // 3. Apply updates to database
        if (Object.keys(bookUpdates).length > 0) {
          await db.from('books').update(bookUpdates).eq('id', bookId)
        }

        // 4. Update library_item fields
        const itemUpdates: any = {}
        if (metadata?.title) itemUpdates.title = metadata.title
        if (metadata?.author) {
          itemUpdates.author_names_first_last = metadata.author
          // Ensure author exists in authors table too
          const { data: existingAuthor } = await db.from('authors').select('id').eq('name', metadata.author).eq('library_id', libraryId).maybeSingle()
          let authorId = existingAuthor?.id
          if (!authorId) {
            authorId = crypto.randomUUID()
            await db.from('authors').insert({ id: authorId, name: metadata.author, library_id: libraryId })
          }
          if (authorId) {
            await db.from('book_authors').upsert({ book_id: bookId, author_id: authorId })
          }
        }
        if (storagePath) itemUpdates.cover_path = storagePath

        if (Object.keys(itemUpdates).length > 0) {
          await db.from('library_items').update(itemUpdates).eq('id', libraryItemId)
        }
      })
      .catch((err) => console.warn('[upload] auto-match failed:', err?.message))
  }

  return NextResponse.json({ success: true, libraryItemId, bookId })
}
