import { createServiceRoleClient } from '@/utils/supabase/service-role'
import { createClient as createSupabaseClient } from '@supabase/supabase-js'
import { NextRequest, NextResponse } from 'next/server'

/**
 * POST /api/upload
 *
 * Receives JSON metadata after files have already been uploaded directly
 * to Supabase Storage from the browser. Creates the DB records:
 *   books → library_items (media_id → books.id) → book_authors / book_series
 *
 * Auth: JWT from Authorization: Bearer header.
 *
 * Body (JSON):
 *   bookId        - UUID pre-generated by the client (storage path prefix)
 *   title         - item title
 *   author        - author name (optional)
 *   series        - series name (optional)
 *   library       - library UUID
 *   mediaType     - 'book' | 'podcast'
 *   files         - array of { name, size, type, storagePath }
 */
export async function POST(request: NextRequest) {
  // ── 1. Verify JWT ─────────────────────────────────────────────────────────
  const authHeader = request.headers.get('authorization')
  const token = authHeader?.startsWith('Bearer ') ? authHeader.slice(7) : null

  if (!token) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  const anonClient = createSupabaseClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
  )
  const { data: { user }, error: userError } = await anonClient.auth.getUser(token)

  if (userError || !user) {
    return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
  }

  // ── 2. Check admin/root ───────────────────────────────────────────────────
  const db = createServiceRoleClient()

  const { data: profile } = await db
    .from('profiles')
    .select('user_type')
    .eq('id', user.id)
    .single()

  if (!profile || !['admin', 'root'].includes(profile.user_type ?? '')) {
    return NextResponse.json({ error: 'Forbidden — admin or root required' }, { status: 403 })
  }

  // ── 3. Parse JSON body ────────────────────────────────────────────────────
  let body: {
    bookId: string
    title: string
    author?: string
    series?: string
    library: string
    mediaType?: string
    files: { name: string; size: number; type: string; storagePath: string }[]
  }

  try {
    body = await request.json()
  } catch {
    return NextResponse.json({ error: 'Invalid JSON body' }, { status: 400 })
  }

  const { bookId, title, author = '', series = '', library: libraryId, mediaType = 'book', files } = body

  if (!bookId || !title || !libraryId || !files?.length) {
    return NextResponse.json({ error: 'Missing required fields: bookId, title, library, files' }, { status: 400 })
  }

  const libraryItemId = crypto.randomUUID()
  const totalSize = files.reduce((sum, f) => sum + f.size, 0)

  // ── 4. Build audio_files JSONB ────────────────────────────────────────────
  const audioFilesJson = files.map((file, i) => ({
    index: i,
    ino: crypto.randomUUID(),
    metadata: {
      filename: file.name,
      ext: '.' + (file.name.split('.').pop()?.toLowerCase() ?? ''),
      path: file.storagePath,
      relPath: file.name,
      size: file.size,
      mtimeMs: Date.now(),
      ctimeMs: Date.now(),
      birthtimeMs: Date.now(),
    },
    addedAt: Date.now(),
    updatedAt: Date.now(),
    trackNumFromMeta: null,
    discNumFromMeta: null,
    trackNumFromFilename: null,
    discNumFromFilename: null,
    manuallyVerified: false,
    invalid: false,
    exclude: false,
    error: null,
    format: null,
    duration: null,
    bitRate: null,
    language: null,
    codec: null,
    timeBase: null,
    channels: null,
    channelLayout: null,
    chapters: [],
    embeddedCoverArt: null,
    metaTags: {},
    mimeType: file.type || 'audio/mpeg',
  }))

  // ── 5. Create book row ────────────────────────────────────────────────────
  const { error: bookError } = await db
    .from('books')
    .insert({ id: bookId, title, audio_files: audioFilesJson })

  if (bookError) {
    console.error('[upload] books insert failed:', bookError)
    return NextResponse.json({ error: `Failed to create book: ${bookError.message}` }, { status: 500 })
  }

  // ── 6. Create library_item row ────────────────────────────────────────────
  const { error: itemError } = await db
    .from('library_items')
    .insert({
      id: libraryItemId,
      library_id: libraryId,
      media_type: mediaType,
      media_id: bookId,
      path: `${libraryId}/${title}`,
      rel_path: title,
      title,
      size: totalSize,
      library_files: audioFilesJson.map((af) => ({
        ino: af.ino,
        metadata: af.metadata,
        addedAt: af.addedAt,
        updatedAt: af.updatedAt,
        isSupplementary: false,
      })),
    })

  if (itemError) {
    console.error('[upload] library_items insert failed:', itemError)
    // Clean up book row and orphaned storage files
    await db.from('books').delete().eq('id', bookId)
    await db.storage.from('audio-files').remove(files.map((f) => f.storagePath))
    return NextResponse.json({ error: `Failed to create library item: ${itemError.message}` }, { status: 500 })
  }

  // ── 7. Author ─────────────────────────────────────────────────────────────
  if (author) {
    const { data: existingAuthor } = await db
      .from('authors')
      .select('id')
      .eq('name', author)
      .eq('library_id', libraryId)
      .maybeSingle()

    let authorId = existingAuthor?.id
    if (!authorId) {
      authorId = crypto.randomUUID()
      const { error: ae } = await db.from('authors').insert({ id: authorId, name: author, library_id: libraryId })
      if (ae) { console.warn('[upload] author insert failed:', ae.message); authorId = undefined }
    }

    if (authorId) {
      await db.from('book_authors').insert({ book_id: bookId, author_id: authorId })
      await db.from('library_items').update({ author_names_first_last: author }).eq('id', libraryItemId)
    }
  }

  // ── 8. Series ─────────────────────────────────────────────────────────────
  if (series) {
    const { data: existingSeries } = await db
      .from('series')
      .select('id')
      .eq('name', series)
      .eq('library_id', libraryId)
      .maybeSingle()

    let seriesId = existingSeries?.id
    if (!seriesId) {
      seriesId = crypto.randomUUID()
      const { error: se } = await db.from('series').insert({ id: seriesId, name: series, library_id: libraryId })
      if (se) { console.warn('[upload] series insert failed:', se.message); seriesId = undefined }
    }

    if (seriesId) {
      await db.from('book_series').insert({ book_id: bookId, series_id: seriesId })
    }
  }

  // ── 9. Auto-fetch cover art (non-blocking) ────────────────────────────────
  // Fire and forget — don't await so the upload response is immediate.
  // The cover will appear after a few seconds once fetched and stored.
  if (mediaType === 'book' && title) {
    fetchBookCover(title, author || undefined)
      .then(async (imageBuffer) => {
        if (!imageBuffer) return
        const storagePath = `${libraryItemId}/cover.jpg`
        const { error: coverErr } = await db.storage
          .from('covers')
          .upload(storagePath, imageBuffer, { upsert: true, contentType: 'image/jpeg' })
        if (coverErr) {
          console.warn('[upload] cover fetch storage failed:', coverErr.message)
          return
        }
        await db.from('library_items').update({ cover_path: storagePath }).eq('id', libraryItemId)
      })
      .catch((err) => console.warn('[upload] cover fetch failed:', err?.message))
  }

  return NextResponse.json({ success: true, libraryItemId, bookId })
}
