import { Project, SyntaxKind, TypeAliasDeclaration, PropertySignature } from 'ts-morph'
import * as fs from 'fs'
import * as path from 'path'

const SUPABASE_TYPES_PATH = path.join(__dirname, '../src/types/supabase.ts')
const OUTPUT_SWIFT_PATH = path.join(__dirname, '../../audiobookphile-app/Sources/Audiobookphile/Core/Models/SupabaseModels.swift')

function mapTypeToSwift(tsType: string): string {
  if (tsType.includes('string')) return 'String'
  if (tsType.includes('number')) return 'Double'
  if (tsType.includes('boolean')) return 'Bool'
  if (tsType.includes('Json')) return 'AnyCodable' // Requires a generic AnyCodable or dictionary
  return 'String' // Fallback
}

function camelCase(str: string): string {
  return str.replace(/_([a-z])/g, (g) => g[1].toUpperCase())
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

async function generateSwiftModels() {
  console.log(`Parsing ${SUPABASE_TYPES_PATH}...`)
  const project = new Project()
  const sourceFile = project.addSourceFileAtPath(SUPABASE_TYPES_PATH)

  const databaseType = sourceFile.getTypeAlias('Database')
  if (!databaseType) throw new Error('Could not find Database type alias')

  const publicProp = databaseType.getTypeNode()?.asKind(SyntaxKind.TypeLiteral)
    ?.getProperty('public')?.getTypeNode()?.asKind(SyntaxKind.TypeLiteral)
  
  const tablesProp = publicProp?.getProperty('Tables')?.getTypeNode()?.asKind(SyntaxKind.TypeLiteral)
  if (!tablesProp) throw new Error('Could not find Tables definition')

  const tables = tablesProp.getMembers().filter(m => m.getKind() === SyntaxKind.PropertySignature) as PropertySignature[]

  let swiftCode = `// Auto-generated by generate-swift-models.ts\n`
  swiftCode += `// Do not edit manually. Generated from Supabase Types.\n\n`
  swiftCode += `import Foundation\nimport AnyCodable\n\n`

  for (const table of tables) {
    const tableName = table.getName().replace(/['"]/g, '')
    const structName = capitalize(camelCase(tableName))

    const rowType = table.getTypeNode()?.asKind(SyntaxKind.TypeLiteral)
      ?.getProperty('Row')?.getTypeNode()?.asKind(SyntaxKind.TypeLiteral)

    if (!rowType) continue

    swiftCode += `public struct ${structName}: Codable, Identifiable, Hashable {\n`
    
    const properties = rowType.getMembers().filter(m => m.getKind() === SyntaxKind.PropertySignature) as PropertySignature[]
    
    // Pass 1: Properties
    for (const prop of properties) {
      const propName = prop.getName().replace(/['"]/g, '')
      const propTypeNode = prop.getTypeNode()
      const typeText = propTypeNode ? propTypeNode.getText() : 'string'
      
      const isOptional = typeText.includes('null')
      const swiftType = mapTypeToSwift(typeText) + (isOptional ? '?' : '')
      const swiftPropName = camelCase(propName)

      swiftCode += `    public var ${swiftPropName}: ${swiftType}\n`
    }
    
    // Pass 2: CodingKeys
    swiftCode += `\n    enum CodingKeys: String, CodingKey {\n`
    for (const prop of properties) {
      const propName = prop.getName().replace(/['"]/g, '')
      const swiftPropName = camelCase(propName)
      if (swiftPropName !== propName) {
        swiftCode += `        case ${swiftPropName} = "${propName}"\n`
      } else {
        swiftCode += `        case ${swiftPropName}\n`
      }
    }
    swiftCode += `    }\n`

    swiftCode += `}\n\n`
  }

  // Ensure output dir exists
  const dir = path.dirname(OUTPUT_SWIFT_PATH)
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true })
  }

  fs.writeFileSync(OUTPUT_SWIFT_PATH, swiftCode)
  console.log(`Successfully generated ${tables.length} Swift models at ${OUTPUT_SWIFT_PATH}`)
}

generateSwiftModels().catch(console.error)
