name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: [self-hosted, macOS]
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Code Review by AI
        uses: anc95/ChatGPT-CodeReview@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # You can also use other models like gpt-4 if you prefer
          MODEL: gpt-3.5-turbo
        with:
          debug: false
          review_comment_lgtm: false
          path_filters: |
            !dist/**
            !**/*.lockb
            !**/*.lock
            !package-lock.json
